Ezyfox dependencies
youngmonkeys/ezyfox pull request #97
Opened 2022-06-02 16:39 UTC by solitarysp

Add dependency Management for Ezyfox

2022-06-02 16:53 UTC, solitarysp commented on ezyfox-dependencies/pom.xml
> +        <thymeleaf-layout-dialect.version>3.0.0</thymeleaf-layout-dialect.version>
Please check version

2022-06-19 07:18 UTC, tvd12 requested changes
@solitarysp PLTAL

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +                </plugin>
2 cái này ít được sử dụng nên bỏ đi em ạ, vì kotlin thì thường là dủng gradle rồi, còn clean thì dùng mặc định

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +            </dependency>
mấy cái này rất hiếm có dự án sử dụng nên có thể bỏ đi em ạ

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +            </dependency>
java cũng sẽ ít dùng cho đồ của microsoft nên có thể bỏ đi em ạ

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +                <version>${mongodb.version}</version>
anh nghĩ là chỉ cần thế này là đủ:

```xml
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>${mongodb.version}</version>
        </dependency>
```

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +            </dependency>
những cái này có thể để scope là test được không em nhỉ?

2022-06-19 07:18 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +            </dependency>
anh nghĩ mấy cái này không cần thiết em ạ, vì mình có kafka_2.12 là đủ rồi

2022-06-25 14:57 UTC, solitarysp commented on ezyfox-dependencies/pom.xml
> +            </dependency>
dependencyManagement chỉ nên định nghĩa verison của các thư viện ạ. Mình không nên định nghĩa scope của thư viện.

2022-06-25 14:57 UTC, solitarysp commented on ezyfox-dependencies/pom.xml
> +            </dependency>
Cho em xin dependency của `kafka_2.12 ` ạ

2022-06-25 15:49 UTC, tvd12 commented on ezyfox-dependencies/pom.xml
> +            </dependency>
đây em: https://mvnrepository.com/artifact/org.apache.kafka/kafka_2.12/2.8.1

2022-06-25 15:54 UTC, solitarysp commented on ezyfox-dependencies/pom.xml
> +            </dependency>
Update

2022-06-26 07:25 UTC, tvd12 approved these changes
LGTM

2022-06-26 07:25 UTC, merged